FROM php:8.0.9-cli
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN docker-php-ext-install bcmath
RUN apt-get update && apt-get install -y unzip
COPY --from=composer:2.1 /usr/bin/composer /usr/bin/composer
RUN mkdir /.composer && chmod 777 /.composer
