services:
    TransactionRepository:
        alias: App\Repository\TransactionRepository
        public: true
    App\Service\ExchangeRate\ExchangeRateInterface:
        alias: App\Service\ExchangeRate\Stub
        public: true
    App\Repository\CurrencyRepositoryInterface:
        alias: App\Repository\CurrencyRepository
        public: true
