imports:                                                                                                                                                                                                           
    - { resource: currencies.yaml }
    - { resource: env.yaml }

# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
    
    App\Runner:
        public: true
        tags: ["app.runner"]

    App\Factory\CurrencyFactory:
        arguments: ['%currencies%']
   
    App\Service\ExchangeRateStub:
        arguments: 
            $rates: '%rates%'

    commission.deposit:
        class: 'App\Service\CommissionConstant'
        arguments:
            $commission: '0.03'
    
    commission.withdraw.business:
        class: 'App\Service\CommissionConstant'
        arguments:
            $commission: '0.5'
    
    commission.withdraw.private:
        class: 'App\Service\CommissionDiscount'
        arguments:
            $commission: '0.3'
            $discountAmount: '1000'
            $discountCurrency: 'EUR'
            $discountCount: 3

    App\Service\CommissionCalc:
        arguments:
            $commissions:
                deposit:
                    business: '@commission.deposit'
                    private: '@commission.deposit'
                withdraw:
                    business: '@commission.withdraw.business'
                    private: '@commission.withdraw.private'

    BenMajor\ExchangeRatesAPI\ExchangeRatesAPI:
        arguments:
            $access_key: '%exchangeratesapi.io.key%'
            $use_ssl: '%exchangeratesapi.io.isPaid%'

    App\Service\ExchangeRateInterface:
        #alias: App\Service\ExchangeRateStub
        alias: App\Service\ExchangeRateApi

    App\Service\ExchangeRateApi:
        arguments:
            $isPaid: '%exchangeratesapi.io.isPaid%'
    App\Service\Reader\CSVReader:
        arguments:
            $fileName: '%filename%'