services:
    TransactionFactory:
        alias: App\Factory\TransactionFactory
        public: true
    App\Service\ExchangeRateInterface:
        alias: App\Service\ExchangeRateStub
        public: true
    App\Factory\CurrencyFactoryInterface:
        alias: App\Factory\CurrencyFactory
        public: true
