services:
    TransactionFactory:
        alias: App\Factory\TransactionFactory
        public: true
    App\Service\ExchangeRate\ExchangeRateInterface:
        alias: App\Service\ExchangeRate\Stub
        public: true
    App\Factory\CurrencyFactoryInterface:
        alias: App\Factory\CurrencyFactory
        public: true
